### ISSUE TITLE
[feature] handling a large number of Point/Multipoint

### ISSUE THREAD

**Issue by kkdd** [mapbox/geojson-vt#115] opened 2018-11-18 08:58 UTC
Hello,
Does geojson-vt have a plan to handle a large number of Point/Multipoint geojson data faster in the future? Its response of panning and zooming feels slow in low zoom levels in a web browser as well as initial indexing:

> indexing 1000000 features: 32380 ms

**Comment by mourner** [comment] 2018-11-18 12:49
Yes. Currently geojson-vt isn't well fitted for point data — for now look at https://github.com/mapbox/supercluster instead. Closing as a duplicate of #8

**Closed by mourner** 2018-11-18 12:49 UTC
