### ISSUE TITLE
geojson(s) duplicating in map

### ISSUE THREAD

**Issue by SeanChristopherConway** [mapbox/geojson-vt#73] opened 2016-09-29 08:18 UTC
Any geojson that I translate to a vector tile seems to duplicate on the map.  I have tested all my geojson using other methods and in geojsonlint so there is no issues on that front. The following code, for example, produces this issue: 
`router.get("/geojson/:z/:x/:y.:format", function (req, res) {
    var z = req.params.z,
        x = req.params.x,
        y = req.params.y;
    var vtpbf = require('vt-pbf');
    var geojsonVt = require('geojson-vt');
    var leftPoint = {
        type: 'Feature',
        properties: {
            "icon": "site"
        },
        geometry: {
            coordinates: [-123.501134, 48.424099],
            type: 'Point'
        }
    };
    var tileindex = geojsonVt(leftPoint);
    var tile = tileindex.getTile(0, 0, 0); //z,x,y produces nothing
    if (tile) {
        var buff = vtpbf.fromGeojsonVt({
            'geojsonLayer': tile
        });
        res.send(buff);
    }
});`
I am then consuming it in my style.json sources as such:

`"sites": {
            "type": "vector",
            "tiles": ["http://localhost:3000/geojson/{z}/{x}/{y}.pbf"],
            "minzoom": 0,
            "maxzoom": 16
        }`

**Comment by SeanChristopherConway** [comment] 2016-09-29 08:23
sorry for the formatting, wasn't playing nice 👎

**Comment by mourner** [comment] 2016-09-29 09:10
I didn't understand the issue, can you describe what exactly happens that you don't expect? Preferably with a minimal test case without servers, `vtpbf`, etc.?

**Comment by SeanChristopherConway** [comment] 2016-09-29 18:49
Sorry for the poor explanation. I am trying to take a geojson, convert it to a geojson vector tile, then  create a pbf using vt-pbf and render it in mapbox gl js. However, when I use this method the geojson does not render properly, as seen in the screenshot. 
![screen shot 2016-09-29 at 12 17 56 am](https://cloud.githubusercontent.com/assets/2946051/18967569/8bd423f6-863a-11e6-8475-c1077dab9ccf.png)

**Comment by SeanChristopherConway** [comment] 2016-09-29 18:50
Whereas it it supposed to look like this, and renders fine using a geojson source or streaming a .mbtiles file using tilelive.
![screen shot 2016-09-29 at 12 18 11 am](https://cloud.githubusercontent.com/assets/2946051/18967653/e76c6570-863a-11e6-955b-3be18286d6b3.png)

**Comment by mourner** [comment] 2016-09-29 18:54
Can you share this GeoJSON file?

**Comment by SeanChristopherConway** [comment] 2016-09-29 19:22
[sites221.geojson.zip](https://github.com/mapbox/geojson-vt/files/501519/sites221.geojson.zip)

**Comment by mourner** [comment] 2016-10-26 16:55
@SeanChristopherConway have you resolved your issue? I haven't had the chance to triage it yet.

**Comment by SeanChristopherConway** [comment] 2016-10-26 16:58
@mourner I know that if I load geojson sources via a url or simply in the stlylejson(which am doing) then it will be loaded off the main thread using mapbox gl js. So no I have not solved it but have found it may not be necessary. However, if I want to use geojson served as a vector tile source I would still like to have this working.

**Comment by SeanChristopherConway** [comment] 2016-10-26 17:00
@mourner In all the examples you only draw the geojson vt to the canvas, would you be able to provide an example of how we can use this as a tile source in a mapbox stylejson? Would be awesome.

**Comment by clouddie** [comment] 2016-11-20 21:25
@mourner @SeanChristopherConway Hi, the same thing is happening to me, on source / style load, my simple line geojson feature, transformed server-side with geojson-vt  then vtpbf, gets duplicated (3x):

![image](https://cloud.githubusercontent.com/assets/20913430/20466241/b79c8222-af6f-11e6-8ff8-612b9ef59039.png)


Here is the file:

`{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"LineString","coordinates":[[114.199297,22.330566],[114.195756,22.327291],[114.194598,22.321495]]},"properties":{"data":{"length":3.4,"diameter":100,"temperature":20},"id":22622,"object_type":"district_cooling","validity_start":null,"validity_end":null,"height":null}}]}`

I have tried as SeanChristopherConway to simply add it via a GeoJSON source, and it works fine, no duplication.

**Comment by mourner** [comment] 2016-11-20 21:32
Could this be a vtpbf issue? cc @anandthakker

**Comment by anandthakker** [comment] 2016-11-21 02:20
@mourner possible, but it's a bit difficult to guess based on the info here.  @clouddie could you possibly provide one or both of the following?

1. A copy of the binary file produced by `vt-pbf` in your server?
2. Example code--both server and client side--that reproduces the issue?

**Comment by clouddie** [comment] 2016-11-21 20:01
Hi @anandthakker , thanks for the help.

(Disclaimer: I am a hobbyist programmer, only code at week-ends, so this might explain why I'm struggling, if you feel I am not skilled enough to explain myself, please do not hesitate to tell me that you don't have time to answer this).

1. Copy of the binary - files : see attached ([vtpbf_output.zip](https://github.com/mapbox/geojson-vt/files/604661/vtpbf_output.zip))- My mapbox-gl-js client does several requests (whereas I am not moving the map an inch:

`http://localhost:3000/citytiles/14/13388/7149.pbf
http://localhost:3000/citytiles/14/13389/7149.pbf
http://localhost:3000/citytiles/14/13387/7149.pbf
http://localhost:3000/citytiles/14/13390/7149.pbf
http://localhost:3000/citytiles/14/13388/7149.pbf
http://localhost:3000/citytiles/14/13387/7149.pbf
http://localhost:3000/citytiles/14/13388/7149.pbf`

I also get this message : `Vector tile source "scenarios" layer "district_cooling" does not use vector tile spec v2 and therefore may have some rendering errors.`

2. Example code ([server code](https://gist.github.com/clouddie/2477cf5bac7f08dfc7f7990e96dd6703)) and ([client code](https://gist.github.com/clouddie/0b6706b3c8ac6036c1c013eb79a78292)) - The client code is slightly weird as I am messing about with Elm and only using mapbox-gl-js through ports

**Comment by mourner** [comment] 2017-02-28 03:30
Closing since this doesn't seem to be strictly a geojson-vt issue. I'll reopen if there's an isolated test case though. My suspicion is on vtpbf.

**Closed by mourner** 2017-02-28 03:30 UTC
Labels: needs more info

**Comment by waterfall49** [comment] 2020-03-25 22:02
check this one https://www.youtube.com/watch?v=gEmOFsglk34&t=26s
