### ISSUE TITLE
z0 tile may include duplicate features

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/geojson-vt#58] opened 2016-05-13 22:06 UTC
Test case:

```
var geojsonvt = require('geojson-vt');
console.log(geojsonvt(
    {"type": "Point", "coordinates": [90, 0]},
    {buffer: 2048, extent: 8192}).getTile(0, 0, 0).features.length);
```

This prints `2` because the point is included twice: one because it's within the normal extent and once because it's within the buffer, which for z0 is wrapping into the opposite side of the tile. It seems to me the buffer should be ignored for z0, rather than generating duplicate features. (What does mapnik do in this case?)

cc @mourner @flippmoke

**Comment by ericfischer** [comment] 2016-05-13 22:16
For whatever it's worth, Tippecanoe only includes this point once in the z0 tile because it only duplicates features that actually fall at least partially west of -180 or east of 180, regardless of the buffer size. But it would be more consistent with other behavior to have the buffer wrap around, since, if it only appears once, a big marker near the date line would only get drawn on one side of it.

**Comment by jfirebaugh** [comment] 2016-05-14 02:33
The reason I stumbled on this was testing Mapbox GL `queryRenderedFeatures` on a GeoJSON source at z0, where I wasn't expecting to see duplicates. But I can see an argument for how duplicating the feature at z0 is consistent with `queryRenderedFeatures` at higher zoom levels, where feature results may be duplicated across tiles.

**Comment by mourner** [comment] 2016-05-14 06:52
I don't think features in the buffer should be ignored even on z0. Imagine having a point feature within unbuffered z0 but very close to the dateline. We render tiles clipped to exact boundaries, but have a buffer because features that visually extend to adjacent tiles should not be cut off — for example, a circle with a big enough radius. For the example of a circle near the dateline, if you don't duplicate the feature, it won't come in the buffer on the other size of the tile, which may lead to unwanted clipping because the z0 tile wraps around the world. 

I'll close this as "working as designed", but will reopen if there's a convincing reason to deduplicate on z0 tile.

**Closed by mourner** 2016-05-14 06:52 UTC
